name: Hello World

on:
  workflow_dispatch:

concurrency:
  group: hello-world
  cancel-in-progress: false

permissions: {} # deny by default

jobs:
  hello:
    name: Print hello world
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello World"
