name: Hello World

on:
  workflow_dispatch:
  push:

concurrency:
  group: hello-world
  cancel-in-progress: false

permissions: {} # deny by default

jobs:
  hello:
    name: Print hello world
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Print hello world
        run: echo "Hello World"
